nginx:
    image: nginx:v1.0
    links:
        - mysql
        - redis
        - phpfpm
        - swoole
    ports:
        - "80:80"
        - "443:443"
    volumes:
        - /var/www:/usr/share/nginx/html
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./nginx.d:/etc/nginx/conf.d

mysql:
    image: index.alauda.cn/library/mysql
    environment:
        MYSQL_ROOT_PASSWORD: qazasdedc123
    ports:
        - "3307:3306"
    volumes:
        - ./mysql.cnf:/etc/mysql/my.cnf
        - ./mysql.d:/etc/mysql/conf.d
        - /var/mysql:/var/lib/mysql

redis:
    image: index.alauda.cn/library/redis
    ports:
        - "6379:6379"

phpfpm:
    image: php-fpm:v5.6
    links:
        - mysql
        - redis
    volumes:
        - /var/www:/var/www/html
        - /var/phpDocker:/root/ying
    ports:
        - "9000:9000"
swoole:
    image: swoole-server:0.1
    ports: 
        - "8080:8080"
    volumes:
        - /var/www:/var/www/html
